Repository boostcampwm-2024/refactor-web40-juchumjuchum, pull requests merged in 2025-01, with the labels that each got.

#4 Task #1 logger
  package-lock.json
  package.json
  packages/backend/docs/logger.MD
  packages/backend/src/common/interceptor/HttpTraceInterceptor.ts
  packages/backend/src/configs/logger.config.ts
  packages/backend/src/configs/typeormConfig.ts
  packages/backend/src/main.ts
  packages/frontend/src/apis/queries/stocks/schema.ts
  packages/frontend/src/apis/utils/get.ts
  packages/frontend/src/sockets/config.ts
Labels: enhancement

#3 구글 로그인 기능 개선
  packages/backend/src/auth/google/googleAuth.controller.ts
  packages/backend/src/user/domain/user.entity.ts
  packages/frontend/src/pages/login/Login.tsx
Labels: enhancement

#6 배치처리를 통한 서버초기화 성능개선
  packages/backend/docs/query-boom.MD
  packages/backend/src/common/interceptor/HttpTraceInterceptor.ts
  packages/backend/src/scraper/korea-stock-info/korea-stock-info.service.ts
Labels: enhancement

#8 Refactor #7 solid, ocp 원칙 적용
  packages/backend/docs/ocp.MD
  packages/backend/docs/solid.MD
  packages/backend/src/stock/stock.controller.ts
  packages/backend/src/stock/stock.module.ts
  packages/backend/src/stock/stock.service.ts
  packages/backend/src/stock/strategy/StockSortStrategy.ts
  packages/frontend/src/apis/queries/stocks/useGetStocksByPrice.ts
  packages/frontend/src/apis/queries/stocks/useStockQueries.ts
Labels: enhancement

#16 에러발생시 서버가 죽는 현상 수정
  packages/backend/src/common/interceptor/HttpTraceInterceptor.ts
  packages/backend/src/main.ts
Labels: bug

#13 배포 환경에서 웹 소캣 연결 실패 문제 해결
  cz-config.js
  packages/backend/src/main.ts
  packages/frontend/src/sockets/config.ts
Labels: enhancement

#19 배포용 브랜치를 dev에서 main으로 변경
  .github/workflows/deploy-main.yml
Labels: enhancement

#22 Task #17 쿼리튜닝,동시성점검
  README.md
  package-lock.json
  packages/backend/src/stock/domain/stock-test.entity.ts
  packages/backend/src/stock/domain/stock.entity.ts
  packages/backend/src/stock/stock.service.concurrency.spec.ts
  yarn.lock
Labels: enhancement

#25 stock service test 개선
  packages/backend/src/stock/stock.service.spec.ts
Labels: BE, refactor

#33 배포 환경에서 프론트엔드 환경변수 적용 실패 문제 해결
  .github/workflows/deploy-main.yml
Labels: bugfix, deployment

#34 배포용 pr
  .github/workflows/deploy-main.yml
Labels: deployment

#36 StockService 단위 테스트를 변경된 StockService 구조에 맞게 변경
  packages/backend/src/stock/stock.service.spec.ts
Labels: BE, test
