Repository boostcampwm-2024/refactor-web40-juchumjuchum, pull requests merged in 2025-02, with the labels that each got.

#40 Task #37 종목별 뉴스 쓰기/조회구현, 프런트 구현
  packages/backend/docs/serviceExplain.md
  packages/backend/serviceExplain.md
  packages/backend/src/app.module.ts
  packages/backend/src/news/domain/stockNews.entity.ts
  packages/backend/src/news/dto/stockNews.dto.ts
  packages/backend/src/news/stockNews.controller.ts
  packages/backend/src/news/stockNews.module.ts
  packages/backend/src/news/stockNews.service.spec.ts
  packages/backend/src/news/stockNews.service.ts
  packages/backend/src/stock/domain/stock.entity.ts
  packages/frontend/src/pages/stock-detail/components/NewsButton.tsx
  packages/frontend/src/pages/stock-detail/components/StockDetailHeader.tsx
Labels: FE, BE

#41 뉴스 요약 Clova API 연동
  packages/backend/src/news/newsClova.service.ts
  packages/backend/src/news/sample.ts
Labels: BE, AI, feature

#42 Feat #38 add news api
  package-lock.json
  packages/backend/package.json
  packages/backend/src/crawling/crawling.service.ts
  packages/backend/src/crawling/crawling.ts
  packages/backend/src/crawling/dto/crawlNewsItem.dto.ts
  packages/backend/src/crawling/dto/crawlingData.dto.ts
  packages/backend/src/crawling/dto/newsInfoDto.ts
  packages/backend/src/crawling/dto/newsItemDto.ts
  packages/backend/src/crawling/news.info.ts
  yarn.lock
Labels: BE

#44 클로바 요약 모델 변경
  packages/backend/src/news/newsClova.service.ts
  packages/backend/src/news/sample.ts
Labels: BE, AI

#46 Task #45 news ai cicd
  packages/backend/src/main.ts
  packages/backend/src/news/StockNewsOrchestrationService.ts
  packages/backend/src/news/dto/crawlNewsItem.dto.ts
  packages/backend/src/news/dto/crawlingData.dto.ts
  packages/backend/src/news/dto/newsInfoDto.ts
  packages/backend/src/news/dto/newsItemDto.ts
  packages/backend/src/news/newsCrawling.service.ts
  packages/backend/src/news/newsSummary.service.ts
  packages/backend/src/news/stockNews.controller.ts
  packages/backend/src/news/stockNews.module.ts
  packages/backend/src/news/stockNews.repository.spec.ts
  packages/backend/src/news/stockNews.repository.ts
  yarn.lock
Labels: AI

#48 fix: cors 오류
  packages/frontend/src/pages/stock-detail/components/NewsButton.tsx
Labels: bugfix

#52 Task #50 ai error fix
  packages/backend/docs/aiDB.MD
  packages/backend/src/configs/typeormConfig.ts
  packages/backend/src/news/StockNewsOrchestrationService.ts
  packages/backend/src/news/newsCrawling.service.ts
  packages/backend/src/news/newsSummary.service.ts
  packages/frontend/src/pages/stock-detail/components/NewsButton.tsx
Labels: bug, AI

#51 클로바 뉴스 요약 형식 문제 해결 시도
  packages/backend/src/configs/typeormConfig.ts
  packages/backend/src/news/StockNewsOrchestrationService.ts
  packages/backend/src/news/newsSummary.service.ts
Labels: bug, AI

#58 클로바 응답 검증 로직 개선
  packages/backend/src/news/StockNewsOrchestrationService.ts
  packages/backend/src/news/newsSummary.service.spec.ts
  packages/backend/src/news/newsSummary.service.ts
Labels: BE, refactor, test

#59 fix: stock detail에서 삼성전자종목의 가격이 매우 깜빡이는 버그 수정
  packages/backend/src/stock/stock.gateway.ts
Labels: bug

#61 chore: [FE] build 옵션 수정(사용하지 않는 변수때문에 빌드가 안됨)
  packages/backend/src/stock/stock.gateway.ts
  packages/frontend/tsconfig.app.json
Labels: bug

#65 Task #64 market cap top10 data insert
  packages/backend/src/configs/logger.config.ts
  packages/backend/src/scraper/openapi/api/openapiLiveData.api.ts
  packages/backend/src/stock/stock.gateway.ts
Labels: BE

#67 NewsSummaryService 커스텀 에러 구현
  packages/backend/src/news/StockNewsOrchestrationService.ts
  packages/backend/src/news/error/formatErrorMessage.ts
  packages/backend/src/news/error/newsSummary.error.ts
  packages/backend/src/news/newsSummary.service.spec.ts
  packages/backend/src/news/newsSummary.service.ts
Labels: BE, feature, test

#72 dev to main
  packages/frontend/src/pages/stock-detail/hooks/useChart.ts
Labels: deployment

#74 특정 종목만 주식 상세 정보가 렌더링 되지 않는 이슈 해결
  packages/frontend/src/pages/stock-detail/StockMetricsPanel.tsx
Labels: FE, bugfix

#80 서버가 죽는 이유를 파악하기 위한 커스텀 로거 구현
  packages/backend/src/app.module.ts
  packages/backend/src/common/logger/connectionMonitor.service.ts
  packages/backend/src/common/logger/customLogger.module.ts
  packages/backend/src/common/logger/customLogger.ts
  packages/backend/src/configs/logger.config.ts
  packages/backend/src/stock/stock.gateway.ts
  packages/backend/src/stock/stock.module.ts
  packages/backend/src/stock/stock.service.spec.ts
  packages/backend/src/stock/stock.service.ts
  packages/backend/src/stock/stockData.service.ts
  packages/backend/src/stock/stockDetail.service.spec.ts
  packages/backend/src/stock/stockDetail.service.ts
  packages/backend/src/stock/stockLiveData.subscriber.ts
  packages/backend/src/stock/stockRateIndex.service.spec.ts
  packages/backend/src/stock/stockRateIndex.service.ts
Labels: BE, feature

#79 feat: [FE] 메인페이지에 호재/악재 표시
  packages/frontend/src/apis/queries/stocks/useStockQueries.ts
  packages/frontend/src/pages/stocks/Stocks.tsx
  packages/frontend/src/pages/stocks/components/StockInfoCard.tsx
  src/frontend/src/components/StockInfoCard.tsx
  src/frontend/src/components/StockNews.tsx
  src/frontend/src/pages/stocks.tsx
Labels: FE

#82 Task #81 호재/악재 프롬프트 수정, fe 구현
  packages/backend/src/news/StockNewsOrchestrationService.ts
  packages/backend/src/news/domain/stockNews.entity.ts
  packages/backend/src/news/dto/stockNews.dto.ts
  packages/backend/src/news/error/newsLinkNotExist.error.ts
  packages/backend/src/news/newsSummary.service.ts
  packages/backend/src/news/stockNews.repository.ts
  packages/frontend/src/apis/queries/stocks/useStockQueries.ts
  packages/frontend/src/components/NewsSummary.tsx
  packages/frontend/src/pages/stock-detail/components/NewsButton.tsx
  packages/frontend/src/pages/stock-detail/components/StockDetailHeader.tsx
  packages/frontend/src/pages/stocks/components/StockInfoCard.tsx
Labels: FE, AI

#83 서버가 죽는 에러 해결 1차 시도
  .prettierrc
  packages/backend/src/common/logger/customLogger.ts
  packages/backend/src/configs/typeormConfig.ts
  packages/backend/src/scraper/korea-stock-info/korea-stock-info.service.ts
  packages/backend/src/scraper/openapi/api/openapiDetailData.api.ts
  packages/backend/src/scraper/openapi/api/openapiFluctuationData.api.ts
  packages/backend/src/scraper/openapi/api/openapiIndex.api.ts
  packages/backend/src/scraper/openapi/api/openapiLiveData.api.ts
  packages/backend/src/scraper/openapi/api/openapiMinuteData.api.ts
  packages/backend/src/scraper/openapi/api/openapiPeriodData.api.ts
  packages/backend/src/scraper/openapi/api/openapiRankView.api.ts
  packages/backend/src/scraper/openapi/api/openapiToken.api.ts
  packages/backend/src/scraper/openapi/liveData.service.ts
  packages/backend/src/scraper/openapi/queue/openapi.queue.ts
  packages/backend/src/scraper/openapi/websocket/websocketClient.websocket.ts
  packages/backend/src/scraper/scraper.module.ts
Labels: BE, bugfix

#84 dev to main
  .prettierrc
  packages/backend/src/app.module.ts
  packages/backend/src/common/logger/connectionMonitor.service.ts
  packages/backend/src/common/logger/customLogger.module.ts
  packages/backend/src/common/logger/customLogger.ts
  packages/backend/src/configs/logger.config.ts
  packages/backend/src/configs/typeormConfig.ts
  packages/backend/src/news/StockNewsOrchestrationService.ts
  packages/backend/src/news/domain/stockNews.entity.ts
  packages/backend/src/news/dto/stockNews.dto.ts
  packages/backend/src/news/error/newsLinkNotExist.error.ts
  packages/backend/src/news/newsCrawling.service.ts
  packages/backend/src/news/newsSummary.service.ts
  packages/backend/src/news/stockNews.repository.ts
  packages/backend/src/scraper/korea-stock-info/korea-stock-info.service.ts
  packages/backend/src/scraper/openapi/api/openapiDetailData.api.ts
  packages/backend/src/scraper/openapi/api/openapiFluctuationData.api.ts
  packages/backend/src/scraper/openapi/api/openapiIndex.api.ts
  packages/backend/src/scraper/openapi/api/openapiLiveData.api.ts
  packages/backend/src/scraper/openapi/api/openapiMinuteData.api.ts
  packages/backend/src/scraper/openapi/api/openapiPeriodData.api.ts
  packages/backend/src/scraper/openapi/api/openapiRankView.api.ts
  packages/backend/src/scraper/openapi/api/openapiToken.api.ts
  packages/backend/src/scraper/openapi/liveData.service.ts
  packages/backend/src/scraper/openapi/queue/openapi.queue.ts
  packages/backend/src/scraper/openapi/websocket/websocketClient.websocket.ts
  packages/backend/src/scraper/scraper.module.ts
  packages/backend/src/stock/stock.gateway.ts
  packages/backend/src/stock/stock.module.ts
  packages/backend/src/stock/stock.service.spec.ts
  packages/backend/src/stock/stock.service.ts
  packages/backend/src/stock/stockData.service.ts
  packages/backend/src/stock/stockDetail.service.spec.ts
  packages/backend/src/stock/stockDetail.service.ts
  packages/backend/src/stock/stockLiveData.subscriber.ts
  packages/backend/src/stock/stockRateIndex.service.spec.ts
  packages/backend/src/stock/stockRateIndex.service.ts
  packages/frontend/src/apis/queries/stocks/useStockQueries.ts
  packages/frontend/src/components/NewsSummary.tsx
  packages/frontend/src/pages/stock-detail/StockMetricsPanel.tsx
  packages/frontend/src/pages/stock-detail/components/NewsButton.tsx
  packages/frontend/src/pages/stock-detail/components/StockDetailHeader.tsx
  packages/frontend/src/pages/stocks/Stocks.tsx
  packages/frontend/src/pages/stocks/components/StockInfoCard.tsx
  src/frontend/src/components/StockInfoCard.tsx
  src/frontend/src/components/StockNews.tsx
  src/frontend/src/pages/stocks.tsx
Labels: deployment

#85 hotfix: [FE] frontend 빌드 안되는 현상 수정
  packages/frontend/src/apis/queries/stocks/schema.ts
Labels: bugfix

#88 배포 환경 typeorm config에 connection 제한 변경
  packages/backend/src/configs/typeormConfig.ts
Labels: BE, deployment

#89 dev to main
  packages/backend/src/configs/typeormConfig.ts
Labels: deployment

#96 뉴스 요약 관련 UI 개선
  packages/backend/src/news/domain/stockNews.entity.ts
  packages/backend/src/news/dto/stockNews.dto.ts
  packages/backend/src/news/newsSummary.service.ts
  packages/backend/src/news/stockNews.repository.ts
  packages/backend/src/scraper/openapi/queue/openapi.queue.ts
  packages/frontend/src/components/NewsSummary.tsx
  packages/frontend/src/index.css
  packages/frontend/src/pages/stock-detail/components/NewsButton.tsx
  packages/frontend/src/pages/stock-detail/components/StockDetailHeader.tsx
  packages/frontend/src/pages/stocks/components/StockInfoCard.tsx
  packages/frontend/src/utils/formatDate.ts
  packages/frontend/tailwind.config.ts
Labels: FE, BE, refactor, feature

#95 Task #91 요약대상종목 동적결정, 요약 프롬프트 개선
  packages/backend/src/news/StockNewsOrchestrationService.ts
  packages/backend/src/news/error/newsLinkNotExist.error.ts
  packages/backend/src/news/newsSummary.service.ts
  packages/backend/src/news/stockNews.module.ts
Labels: BE, AI

#98 Hotfix #00 cron,fe
  packages/backend/src/news/StockNewsOrchestrationService.ts
  packages/frontend/src/pages/stock-detail/components/StockDetailHeader.tsx
  packages/frontend/src/pages/stocks/components/StockInfoCard.tsx
  yarn.lock
Labels: bugfix

#99 hotfix: Failed to initialize transformer
  packages/backend/Dockerfile
Labels: bugfix, deployment

#101 hotfix: Ort::Exception
  packages/backend/Dockerfile
Labels: bugfix, deployment
